; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:default]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = lilygo_t5s3_pro
framework = arduino
extra_scripts = 
	pre:tools/patch_epdiy.py
	pre:tools/patch_tinyxml2.py
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder, time
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_SPIRAM_MODE_OCT=1
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_LOOP_STACK_SIZE=16384
	-I${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src
lib_deps = 
	Network
	https://github.com/vroland/epdiy.git#main
	lewisxhe/SensorLib@^0.2.0
	bblanchon/ArduinoJson@^6
	https://github.com/bitbank2/JPEGDEC.git
	https://github.com/bitbank2/PNGdec.git
	https://github.com/leethomason/tinyxml2.git#10.0.0
	ricmoo/QRCode@^0.0.1
lib_ldf_mode = deep+

[env:gh_release]
extends = env:default
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_SPIRAM_MODE_OCT=1
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_LOOP_STACK_SIZE=16384
	-DFIRMWARE_VERSION='"${sysenv.RELEASE_TAG}"'
	-I${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src
